

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false


exclude:
  - attic
  - README.md
  - TODOS.md


safe: true
lsi: false


plugins:
- jekyll-remote-theme

remote_theme: slideshow-s9/jekyll-books-theme
